// vim: textwidth=72
NOTE
====
Bard has had a major update. I ecourage you to read this document (the
man page) again. It should be better and easier to work with,
facilitating separation between the format script and the bard units,
but it will require you rethink some of your units. You can see some
example in my
[dotfiles](https://github.com/DelusionalLogic/dotfiles/tree/bspwm/bard/.config/bard)


BARD(1)
=======
:doctype: manpage


NAME
----
bard - Manages lemonboy bar with atomic units


SYNOPSIS
--------
*bard* ['OPTIONS']


DESCRIPTION
-----------
The bard(1) daemon manages, parses, formats, and prints information to
lemonbar.


OPTIONS
-------
*-c, --config*='CONFIG'::
    The configuration directory. The directory is expected to contain
	the main 'bard.conf' configuration file
	(see <<X1, *GLOBAL CONFIGURATION*>>). It should also contain the 
	'left', 'center', and 'right' directories, each containing the unit
	files for that alignment (see <<X2, *UNIT CONFIGURATION*>>).


SYNTAX
------
Bard(1) uses the ini format for configuration files. Syntax:

[Group]::
    Option="Value"

the quotes around Value are optional, although space before and after
will be stripped if the quotes are omitted. In this document options
will be denoted:

*Group:Option*::
    Description


[[X1]]
GLOBAL CONFIGURATION (bard.conf)
--------------------------------
The bard(1) global 'bard.conf' file determines the global options for
bard(1). Options:

*display:separator*::
	A string to insert between each unit output. (OPTIONAL, default="
	| ", EXPANDS)

*display:font*::
	The default font to use when units reset the used font. (REQUIRED)

*bar:path*::
	The path to the lemonbar. This does search through the path
	(REQUIRED)

*bar:geometry*::
	The geometry string to pass on to lemonbar. The format for this is
	widthxheight+x+y. (OPTIONAL, default=NULL)

*bar:background*::
	The background to pass to lemonbar. The format is '#AARRGGBB'.
	(OPTIONAL, default=NULL, EXPANDS)

*bar:foreground*::
	The foreground to pass to lemonbar. The format is '#AARRGGBB'.
	(OPTIONAL, default=NULL, EXPANDS)

[[X2]]
UNIT CONFIGURATION
------------------
The 'left', 'right', and 'center' directories contain unit
configurations.  Options:

*unit:name*::
	The name of the unit. Mainly used for error reporting. (REQUIRED)

*unit:type*::
	The type of the unit. Can be 'poll' or 'running'. A 'poll' unit will
	run about every *display:interval* seconds passing the entire output
	into the unit formatting (see <<X3, *FORMATTING*>>). 'running' units
	should never exit. They require a *process:delimiter*, [[delim]]when
	this string is encountered in the output stream the output is ended
	and passed into the unit formatting step (see <<X3, *FORMATTING*>>).
	(OPTIONAL, default=poll)

*process:delimiter*::
	This is only used for running processes. See <<delim, above>> for
	what this does. (OPTIONAL, default="\n")

*display:command*::
	The command to execute. For 'running' processes this command should
	never exit.  For 'poll' units this is the command that will be run
	every iteration of the unit, and should exit. (REQUIRED)

*display:regex*::
	The regex to match the output on, in PCRE syntax.  Groups are
	supported, they are explained further in <<X3, *FORMATTING*>>.
	(OPTIONAL, default=NULL)

*display:advformat*::
	This is a boolean value. True if advanced formatting is used, false
	if not.  Please read <<X3, *FORMATTING*>> for further explanation.
	(OPTIONAL, default=false)

*display:format*::
	The formatting string/program. If *display:advformat* is true this
	will be shell expanded and executed. This is once against best
	explained in <<X3, *FORMATTING*>>. (REQUIRED)

*display:interval*::
	The interval between iterations of *display:command* in 'poll'
	units.  The guarantee is that the unit will not be run before this
	time, it might not be exactly on time though. Ignored for running
	units (OPTIONAL, default=10)

*font:<name>*::
	Allows you to specify unit specific fonts. These can be used in the
	format string. The option name is user specified, multiple fonts are
	supported.  The option name is used to denote the font in the format
	string.  (OPTIONAL, default=NULL)

*env:<name>*::
	For advanced format units. Sets variable <name> to the given value
	when executing the *display:format* command. This is the main way of
	getting data from bard into the formatting script. (OPTIONAL,
	default=NULL, EXPANDED)

[[X3]]
FORMATTING
----------

*Command Execution*::
	For 'poll' units this is done after *display:interval* time. For
	'running' units it's every time the *process:delimiter* string is
	observed. If the output is identical to the previous run the rest of
	the pipeline will not be invoked, and the bar will not be refreshed.
	If the command string is empty, the execution is skipped and nothing
	is passed to the following steps.

*Regex*::
	After the command execution (or after encountering a delimiter for
	a running unit), bard will pass the command output through a PCRE
	regex, specified as *display:regex*. The matches/groups of the regex
	are put into a bard array, with the keys of the indexes of the
	matches. Index 1 is always the entire command output, which is
	especially useful for times where a regex doesn't provide enough
	flexibility.

*bard Arrays*::
	bard has support for different kinds of data input. Some of the data
	comes from the command -> regex parsing. Other is extracted from
	the Xorg server. The bard syntax for expanding data inside of an
	array is "$<arrayname>[<key>]" Bard currently has the following
	arrays:
	xcolor;;
		I'm a ricer. I like to match the colors of all my applications,
		and I spent a lot of my time in the terminal. bard helps me rice
		easier by having direct support for Xrdb colors. (see <<X4,
		*COLORS*>> for available colors)
	font;;
		The font indexes of the fonts specified in the unit
		definition
	regex;;
		The output from the regex matching

*Simple Formatting*::
	Simple formatting is, as the name suggests, a less powerful, but
	easy way for getting some text formatted. It works by expanding the
	bard arrays inside the string.

*Advanced Formatting*::
	Advanced formatting uses an external script or program to give the
	user more control over how the data is formatted. In advanced
	formatting mode the format script first shell expanded. After
	expansion the scrips is run, with the environment variables defined
	in the env section. To pass data from bard into the format script
	the environment variable values are "bard expanded". Any data coming from
	the script is passed into lemonbar directly.


[[X4]]
COLOR NAMES
-----------
Color names listed in order from 0 to 15::
    black
	red
	green
	yellow
	blue
	magenta
	cyan
	white
	grey
	brightred
	brightgreen
	brightyellow
	brightblue
	brightmagenta
	brightcyan
	brightwhite


EXIT STATUS
-----------
*0*::
    Success


AUTHOR
------
bard is written by Jesper Jensen (Delusional Logic)


COPYING
-------
Copyright \(C) 2015 Jesper Jensen. Free use of this software is
granted under the terms of the GNU General Public License (GPL).
